---

- name: Enable Backports repository.
  apt_repository:
    repo: "deb http://http.debian.net/debian {{ansible_distribution_release}}-backports main"
    state: present
  when: ansible_distribution_version | int < 9

- name: Update apt cache.
  apt:
    update_cache: true
    cache_valid_time: 86400

- name: Install Ansible.
  apt:
    name: ansible
    state: present
